//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft
        ///Corporation
        ///is
        ///an
        ///American
        ///multinational
        ///technology
        ///corporation
        ///which
        ///produces
        ///computer
        ///software
        ///consumer
        ///electronics
        ///personal
        ///computers
        ///and
        ///related
        ///services
        ///Its
        ///best
        ///known
        ///products
        ///are
        ///the
        ///Windows
        ///line
        ///of
        ///operating
        ///systems
        ///Office
        ///suite
        ///Internet
        ///Explorer
        ///Edge
        ///web
        ///browsers
        ///flagship
        ///hardware
        ///Xbox
        ///video
        ///game
        ///consoles
        ///Surface
        ///lineup
        ///touchscreen
        ///ranked
        ///No
        ///in
        ///Fortune
        ///rankings
        ///largest
        ///United
        ///States
        ///corporations
        ///by
        ///total
        ///revenue
        ///it
        ///was
        ///worlds
        ///ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Random_words_en {
            get {
                return ResourceManager.GetString("Random_words_en", resourceCulture);
            }
        }
    }
}
